[package]
name                    = "emdocs"
description             = "A client for the emdocs p2p online text buffer sharing protocol."
authors                 = ["Danny McClanahan <dmcC2@hypnicjerk.ai>"]
license                 = "AGPL-3.0-or-later"
repository              = "https://github.com/cosmicexplorer/emdocs"
version                 = "0.0.0"
edition                 = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
emdocs-protocol = { path = "protocol" }

[workspace]
resolver = "2"
members = [
  ".",
  "protocol",
]
default-members = [
  ".",
  "protocol",
]
